### PR TITLE
Certify values fix

### PR DESCRIPTION
**Pull request by jreniel**
Provide fix for certifyvalue() and certify.py lint.

### CODE REVIEW

**Comment by dengwirda** [comment]
@jreniel I'm moving the `jigsawpy` implementation over to [jigsaw-python](https://github.com/dengwirda/jigsaw-python), so that I only need to maintain a single, general-purpose `python` interface. All of the functionality should be consistent with what had been here in `jigsaw-geo-python` though.

As of https://github.com/dengwirda/jigsaw-python/commit/55d391ef07035460ef580a0b91d031754841113d this should include fixes for `certify.py`. In the related changes you made here to `savemsh.py` I can see the code for `VALUE` arrays is slightly different, but it looks to be functionally equivalent to what was there. Is there a bug that needs to be addressed?

**Comment by jreniel** [comment]
@dengwirda Thanks for taking a look at this. The savevalue() function was not writting the arrays correctly to file, and in certify.py there were arguments missing in some functions calls. The certify.py values fix was simple (add the arguments) so you already caught that one probably, but the save value fix was not behaving correctly. In any case, both cases were actual bugs from my perspective.

**Comment by dengwirda** [comment]
@jreniel No worries -- I can't currently see what the issue with `savemsh.py` may be, but if you find a problem with the new `jigsaw-python` let me know and I'll revisit this. If you do find an error, please send through details for a test case so that I can reproduce at my end -- this'd be a great help!

**Comment by jreniel** [comment]
@dengwirda I had to dig into my memory to remember what exactly the problem was, but I believe it is the following: line 111 of the original says:  for ipos in range(mesh.value.size): but it should say  for ipos in range(npos):. This is because size is npos*nval. Then line 113 of the original says for ival in range(nval-1): when it should say for ival in range(nval)

The problem is that you will be able to write a file, but loadmsh() will fail to read it afterwards. This only affects saving euclidean-grid types. To reproduce, write an euclidean-grid then try to re-read it.

**Comment by jreniel** [comment]
@dengwirda  On the other hand, I am good if you want to close this now, and then when I test the new code I can open a new issue with more information. I am currently working on another module and I haven't done a lot of new testing, because after these minor fixes, it all seemed to be working pretty stable.

**Comment by dengwirda** [comment]
@jreniel I've done some quick tests with `-grid` type spacing definitions, and don't at present see any issues saving / loading the data etc. There were a few inter-related changes for `jigsaw-python`, so perhaps this was cleaned up elsewhere. At any rate, I'll close this now, but feel free to re-open if you find an issue.

**Pull request closed without merging**
