### PR TITLE
Suggestion: conform to PEP8 code style

### PR DESCRIPTION
**Pull request by xylar**
I would highly recommend following the PEP8 code style:
https://www.python.org/dev/peps/pep-0008/

There is a package, `autopep8`, that does a nice job of modifying your code to automatically conform to the style:
```
autopep8 --in-place --aggressive *.py
```
I applied this to all the python code.  Please consider either merging this PR or applying this technique yourself.  It would make your code a lot more readable to me and other python developers.

I use an IDE called `spyder` that can automatically detect PEP8 formatting errors as I develop.  It also flags unused imports and variables (and other coding errors of that nature).  I used this to remove unused variable and imports.  Other IDEs like `pycharm` will also do this (but `pycharm` is, I believe, not open source so I don't use it).

`spyder` also flagged a problem in `certify.py` that I will post a separate issue for.

### CODE REVIEW

**Comment by xylar** [comment]
This PR builds on #5 and should only be merged after that.

**Comment by xylar** [comment]
Just realized I forgot to do this rebase.  Done now.

**Comment by dengwirda** [comment]
Okay, I've had a bash at this. I must say that `PEP8` is perhaps not my favourite thing, but I've passed through `jigsawpy` with `flake8` and have tried to get on board with the formatting.

I've also introduced a `setup.cfg` that flags a few `PEP8` rules to ignore though. Currently, there are some `PEP8` rules I'm not feeling "philosophically aligned" with, but also a few things that I'd prefer not to change for consistency with the rest of `jigsaw` as a project.

In terms of `spyder`, etc though, is the `setup.cfg` enough to squelch any remaining `PEP8` syntax highlighting, or is 100% standardisation necessary?

**Comment by xylar** [comment]
Do what you prefer.  If you don't want to stick with this convention, you don't have to.  If you want to follow parts but not other parts, that's fine, too.  I think spyder, pycharm, etc. might be able to get hints from setup.cfg but I don't think that happens automatically, but don't worry about it.

It took me awhile to come around to PEP8.  If you were writing a pure python code, I would recommend more strongly that you follow it closely.  For this case, do what works best for you.

**Comment by dengwirda** [comment]
Thanks for your thought! I'll revisit this in the future and see whether I can ignore fewer things via `setup.cfg`...

**Pull request closed without merging**
